language: node_js
sudo: false
node_js:
    - "6.14.1"
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g codecov
notifications:
  email:
    recipients:
      - thedaviddias@gmail.com
branches:
  only:
    - master
    - /^greenkeeper/.*$/
script:
    - "grunt"
    - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
    - codecov
