name: CI

on:
  push:
    # Run on pushes to specific branches
    branches:
      - master
      - next
      - beta
      - alpha
    # Do not run on tags
    tags-ignore:
      - '*'
  pull_request:
    # Run on to branches with an open PR
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      # Print current Node.js version
      - run: node --version

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Build
        run: npm run build --if-present
        env:
          CI: true

      - name: Run coverage
        run: npm run test:coverage

      # Upload coverage artifact from Node.js LTS
      - uses: actions/upload-artifact@v2
        if: matrix.os == 'ubuntu-latest' && matrix.node == '12'
        with:
          name: coverage
          path: coverage

  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      # Download coverage artifact
      - uses: actions/download-artifact@v1
        with:
          name: coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/lcov.info
          fail_ci_if_error: true
