name: Coverage

on:
  pull_request:
    branches:
      - master
      - develop
      - beta
  push:
    branches:
      - 'chore/**'
      - 'feat/**'
      - 'fix/**'
      - 'perf/**'
      - 'chore/**'
      - 'refactor/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present
        env:
          CI: true

      - name: Run coverage
        if: matrix.os == 'ubuntu-latest' && matrix.node == '12.x'
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.node == '12.x'
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/lcov.info
          fail_ci_if_error: true
